version: '3.8'

services:
  postgres:
    image: postgres:15  # Utilize a versão que você preferir
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432"
